#!/bin/sh

# credits:
# - misopog (https://github.com/misopog/postinstall)

init() {
    if ! command -v "git" &> /dev/null; then
        echo "install git and rerun the script"
        exit 1
    fi
    git clone https://aur.archlinux.org/yay.git $HOME/yay
    sudo sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf
    (cd $HOME/yay && makepkg -si)
    rm -rf $HOME/yay
}

pkg() {
    packages=()
    while IFS= read -r line; do
        packages+=("$line")
    done < $HOME/postinstall/packages
    
    yay -Syu --noconfirm "${packages[@]}"
}

dotfiles() {
    git clone --bare https://github.com/xaizone/dotfiles.git $HOME/.dotfiles
    mkdir -p $HOME/.local/bin $HOME/.local/share
    function dots {
        /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
    }
    dots checkout -f
    dots config status.showUntrackedFiles no
    
    mkdir -p $HOME/audio $HOME/document $HOME/image $HOME/temp $HOME/video
    xdg-user-dirs-update
    
    sudo sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//;/^#VerbosePkgLists$/s/#//" /etc/pacman.conf
}

suckless() {
    for p in dmenu dwm slock;
    do
        git clone https://github.com/xaizone/${p}.git $HOME/document/${p}
        (cd $HOME/document/${p} && sudo make clean install)
    done
}

network() {
    sudo sh -c "echo -e '[connectivity]\nenabled=false' > /etc/NetworkManager/conf.d/20-connectivity.conf"
    if ! grep -q "localhost" /etc/hosts; then
        sudo sh -c "echo -e '127.0.0.1 localhost\n::1 localhost' >> /etc/hosts"
    fi
}

audio() {
    sudo cp $HOME/postinstall/audio/audient-evo4.conf /usr/share/alsa-card-profile/mixer/profile-sets/
    systemctl --user enable pipewire.socket
    systemctl --user enable pipewire-pulse.socket
    systemctl --user enable wireplumber.service
}

x11() {
    sudo cp $HOME/postinstall/x11/* /etc/X11/xorg.conf.d/
}

end() {
    echo "postinstall script finished, type 'y' for reboot, 'n' to cancel"

    read -r response

    case $response in
        y) reboot ;;
        n)
            echo "reboot cancelled"
            exit 0
            ;;
        *)
            echo "incorrect option selected"
            end
            ;;
    esac

}

init
pkg
dotfiles
suckless
audio
network
x11
end
